import type { SensorReading } from './google-sheets'
import type { Preference, WeatherInput } from './outfit-engine'

export type ClimateRegime={name:string;count:number;temperature:number;humidity:number;pressure:number}
export type HistoricalClimateProfile={sampleSize:number;latestTemperature:number;meanTemperature:number;medianTemperature:number;temperatureStdDev:number;meanHumidity:number;humidityStdDev:number;meanPressure:number;temperatureTrendPerHour:number;humidityTrendPerHour:number;pressureTrendPerHour:number;temperatureEwma:number;effectiveOriginTemperature:number;outlierCount:number;changePointDetected:boolean;windowStart:string;windowEnd:string;dewPoint:number;heatIndex:number;absoluteHumidity:number;forecastTemperatureNextHour:number;driftTemperature:number;duplicateCount:number;samplingRegularity:number;regimes:ClimateRegime[];currentRegime:string;backtest:{naiveMae:number;hybridMae:number;improvementPercentage:number}}
export type DataScienceResult={profile:HistoricalClimateProfile;thermalAdaptationScore:number;confidence:number;confidenceLabel:'baja'|'media'|'alta';garmentScores:{garment:string;score:number;factors:string[]}[];dominantFactors:string[];featureImportance:{feature:string;importance:number}[];counterfactuals:{scenario:string;adaptationScore:number;difference:number;recommendation:string}[]}

const average=(v:number[])=>v.reduce((s,x)=>s+x,0)/Math.max(v.length,1)
const median=(v:number[])=>{const s=[...v].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2}
const deviation=(v:number[],m=average(v))=>Math.sqrt(average(v.map(x=>(x-m)**2)))
const clamp=(v:number,min=0,max=100)=>Math.min(max,Math.max(min,v))
const ewma=(v:number[],alpha=.35)=>v.slice(1).reduce((current,x)=>alpha*x+(1-alpha)*current,v[0])
function slope(points:{time:number;value:number}[]){if(points.length<2)return 0;const o=points[0].time,xs=points.map(p=>(p.time-o)/3_600_000),xm=average(xs),ym=average(points.map(p=>p.value)),d=xs.reduce((s,x)=>s+(x-xm)**2,0);return d?xs.reduce((s,x,i)=>s+(x-xm)*(points[i].value-ym),0)/d:0}
const dewPoint=(t:number,h:number)=>{const a=17.27,b=237.7,g=a*t/(b+t)+Math.log(Math.max(h,1)/100);return b*g/(a-g)}
const heatIndex=(t:number,h:number)=>t<27?t:t+.33*(h/100*6.105*Math.exp(17.27*t/(237.7+t)))-.7-4
const absoluteHumidity=(t:number,h:number)=>6.112*Math.exp(17.67*t/(t+243.5))*h*2.1674/(273.15+t)
function robustOutliers(v:number[]){const m=median(v),mad=median(v.map(x=>Math.abs(x-m)));return v.map(x=>mad>0?Math.abs(x-m)/(1.4826*mad)>3.5:false)}
function cluster(readings:SensorReading[]):{regimes:ClimateRegime[];currentRegime:string}{
  if(readings.length<3)return{regimes:[{name:'Régimen único',count:readings.length,temperature:average(readings.map(r=>r.indoor_temperature)),humidity:average(readings.map(r=>r.indoor_humidity)),pressure:average(readings.map(r=>r.indoor_pressure))}],currentRegime:'Régimen único'}
  const features=readings.map(r=>[r.indoor_temperature,r.indoor_humidity,r.indoor_pressure]),means=[0,1,2].map(i=>average(features.map(f=>f[i]))),stds=[0,1,2].map(i=>deviation(features.map(f=>f[i]))||1),z=features.map(f=>f.map((x,i)=>(x-means[i])/stds[i])),k=Math.min(3,readings.length)
  let centers=Array.from({length:k},(_,i)=>[...z[Math.floor(i*(z.length-1)/Math.max(k-1,1))]])
  let assignments:number[]=[]
  for(let iteration=0;iteration<15;iteration++){assignments=z.map(f=>centers.reduce((best,c,i)=>{const d=c.reduce((s,x,j)=>s+(f[j]-x)**2,0);return d<best.distance?{index:i,distance:d}:best},{index:0,distance:Infinity}).index);centers=centers.map((center,i)=>{const members=z.filter((_,j)=>assignments[j]===i);return members.length?center.map((_,j)=>average(members.map(m=>m[j]))):center})}
  const raw=centers.map((_,i)=>{const members=readings.filter((_,j)=>assignments[j]===i);return{index:i,count:members.length,temperature:average(members.map(r=>r.indoor_temperature)),humidity:average(members.map(r=>r.indoor_humidity)),pressure:average(members.map(r=>r.indoor_pressure))}}).filter(x=>x.count)
  raw.sort((a,b)=>a.temperature-b.temperature);const names=raw.map((x,i)=>({...x,name:raw.length===1?'estable':i===0?'fresco':i===raw.length-1?'cálido':'templado'})),currentIndex=assignments.at(-1),current=names.find(x=>x.index===currentIndex)
  return{regimes:names.map(({name,count,temperature,humidity,pressure})=>({name:`${name} ${humidity>=70?'húmedo':humidity<45?'seco':'moderado'}`,count,temperature,humidity,pressure})),currentRegime:current?`${current.name} ${current.humidity>=70?'húmedo':current.humidity<45?'seco':'moderado'}`:'sin clasificar'}
}
function backtest(values:number[]){if(values.length<4)return{naiveMae:0,hybridMae:0,improvementPercentage:0};let naive=0,hybrid=0,count=0;for(let i=3;i<values.length;i++){const train=values.slice(0,i),actual=values[i],prediction=.5*train.at(-1)!+.3*ewma(train)+.2*median(train);naive+=Math.abs(actual-train.at(-1)!);hybrid+=Math.abs(actual-prediction);count++}const n=naive/count,h=hybrid/count;return{naiveMae:n,hybridMae:h,improvementPercentage:n?((n-h)/n)*100:0}}

export function buildHistoricalProfile(readings:SensorReading[]):HistoricalClimateProfile{
  const valid=readings.filter(r=>Number.isFinite(Date.parse(r.timestamp))&&Number.isFinite(r.indoor_temperature)&&Number.isFinite(r.indoor_humidity)&&Number.isFinite(r.indoor_pressure)).slice(-100);if(!valid.length)throw new Error('No hay histórico válido para construir el perfil climático')
  const temps=valid.map(r=>r.indoor_temperature),hums=valid.map(r=>r.indoor_humidity),pressures=valid.map(r=>r.indoor_pressure),times=valid.map(r=>Date.parse(r.timestamp)),tm=average(temps),med=median(temps),std=deviation(temps,tm),e=ewma(temps),outliers=robustOutliers(temps),half=Math.max(1,Math.floor(temps.length/2)),recent=temps.slice(-half),older=temps.slice(0,half),intervals=times.slice(1).map((t,i)=>(t-times[i])/60_000),intervalMean=average(intervals),regime=cluster(valid)
  const tempTrend=slope(valid.map(r=>({time:Date.parse(r.timestamp),value:r.indoor_temperature}))),latestT=temps.at(-1)!,latestH=hums.at(-1)!
  const recentMean=average(recent),olderMean=average(older),changePointDetected=temps.length>=6&&Math.abs(recentMean-olderMean)>Math.max(1.5,std)
  return{sampleSize:valid.length,latestTemperature:latestT,meanTemperature:tm,medianTemperature:med,temperatureStdDev:std,meanHumidity:average(hums),humidityStdDev:deviation(hums),meanPressure:average(pressures),temperatureTrendPerHour:tempTrend,humidityTrendPerHour:slope(valid.map(r=>({time:Date.parse(r.timestamp),value:r.indoor_humidity}))),pressureTrendPerHour:slope(valid.map(r=>({time:Date.parse(r.timestamp),value:r.indoor_pressure}))),temperatureEwma:e,effectiveOriginTemperature:.5*latestT+.3*e+.2*med,outlierCount:outliers.filter(Boolean).length,changePointDetected,windowStart:valid[0].timestamp,windowEnd:valid.at(-1)!.timestamp,dewPoint:dewPoint(latestT,latestH),heatIndex:heatIndex(latestT,latestH),absoluteHumidity:absoluteHumidity(latestT,latestH),forecastTemperatureNextHour:latestT+clamp(tempTrend,-3,3),driftTemperature:recentMean-olderMean,duplicateCount:times.length-new Set(times).size,samplingRegularity:intervals.length&&intervalMean?clamp(100-deviation(intervals)/intervalMean*100):100,regimes:regime.regimes,currentRegime:regime.currentRegime,backtest:backtest(temps)}
}

function stress(profile:HistoricalClimateProfile,w:WeatherInput,p:Preference){const delta=profile.effectiveOriginTemperature-w.apparentTemp,s={low:-8,medium:0,high:14}[p.coldSensitivity],cold=Math.max(0,delta)*3.5+Math.max(0,w.wind-10)*.8+(w.destHum>=75&&w.apparentTemp<18?8:0)+s+Math.max(0,-profile.temperatureTrendPerHour)*4,heat=Math.max(0,-delta)*3+(w.destHum>=75&&w.apparentTemp>=24?12:0)+(w.uv>=6?8:0)-Math.max(0,s);return{cold,heat,score:Math.round(clamp(Math.max(cold,heat)))}}
function addScore(scores:Map<string,{score:number;factors:string[]}>,garment:string,points:number,factor:string){const current=scores.get(garment)??{score:0,factors:[]};current.score+=points;current.factors.push(`${points>0?'+':''}${points.toFixed(1)}: ${factor}`);scores.set(garment,current)}
export function analyzeRecommendation(profile:HistoricalClimateProfile,w:WeatherInput,p:Preference):DataScienceResult{
  const model=stress(profile,w,p),scores=new Map<string,{score:number;factors:string[]}>();addScore(scores,'capa térmica',model.cold*.7,'estrés por frío');addScore(scores,'chaqueta impermeable',w.precipProb*.55,'probabilidad de lluvia');addScore(scores,'rompevientos',Math.max(0,w.wind-8)*2.4,'velocidad del viento');addScore(scores,'calzado impermeable',w.precipProb*.4+w.precip*8,'lluvia y precipitación');addScore(scores,'tejidos transpirables',model.heat*.75,'estrés por calor y humedad');addScore(scores,'protección solar',w.uv*9,'índice UV');addScore(scores,'capa removible',Math.abs(w.destTemp-profile.effectiveOriginTemperature)*5,'cambio respecto al origen efectivo')
  const garmentScores=[...scores].map(([garment,d])=>({garment,score:Math.round(clamp(d.score)),factors:d.factors})).sort((a,b)=>b.score-a.score),age=Math.max(0,(Date.now()-Date.parse(profile.windowEnd))/60_000),confidence=Math.round(clamp(30+Math.min(profile.sampleSize,50)*.8-Math.min(profile.temperatureStdDev*3,15)-Math.min(age/5,20)+profile.samplingRegularity*.1-profile.outlierCount*2+(p.bodyShape&&p.bodyShape!=='prefer_not'?5:0)))
  const rawImportance=[['diferencia térmica',Math.abs(profile.effectiveOriginTemperature-w.apparentTemp)*3.5],['lluvia',w.precipProb*.3+w.precip*4],['viento',Math.max(0,w.wind-8)*1.2],['humedad',w.destHum>=75?10:3],['UV',w.uv*1.5],['sensibilidad',Math.abs({low:-8,medium:0,high:14}[p.coldSensitivity])]],total=rawImportance.reduce((s,x)=>s+Number(x[1]),0)||1,featureImportance=rawImportance.map(([feature,value])=>({feature:String(feature),importance:Math.round(Number(value)/total*100)})).sort((a,b)=>b.importance-a.importance)
  const scenarios=[{scenario:'Lluvia alta',weather:{...w,precipProb:80,precip:Math.max(w.precip,2)},recommendation:'Añadir impermeable y calzado resistente al agua'},{scenario:'5 °C menos',weather:{...w,destTemp:w.destTemp-5,apparentTemp:w.apparentTemp-5},recommendation:'Aumentar protección térmica'},{scenario:'Viento +10 km/h',weather:{...w,wind:w.wind+10},recommendation:'Evaluar una capa cortaviento'}],counterfactuals=scenarios.map(s=>{const score=stress(profile,s.weather,p).score;return{scenario:s.scenario,adaptationScore:score,difference:score-model.score,recommendation:s.recommendation}})
  const delta=profile.effectiveOriginTemperature-w.apparentTemp,dominantFactors=[delta>3?'destino más frío que el baseline':delta<-3?'destino más cálido que el baseline':'cambio térmico leve',w.precipProb>=60?'lluvia probable':w.wind>=20?'viento fuerte':w.uv>=6?'radiación UV alta':'condiciones moderadas',`régimen de origen ${profile.currentRegime}`]
  return{profile,thermalAdaptationScore:model.score,confidence,confidenceLabel:confidence>=75?'alta':confidence>=50?'media':'baja',garmentScores,dominantFactors,featureImportance,counterfactuals}
}
